apiVersion: intelligence.aipcc-gpuaas.com/v1alpha1
kind: KueueSkill
metadata:
  labels:
    app.kubernetes.io/name: kueue-idle-allocated-gpus
    app.kubernetes.io/managed-by: kustomize
  name: kueue-idle-allocated-gpus
spec:
  skillconfigref:
    name: "kueue-intelligence-kueue-idle-allocated-gpus"
