resources:
- manager.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: controller
  newName: ghcr.io/khieron/khieron
  newTag: v0.1.3-2-g99b2158-dirty

generatorOptions:
  disableNameSuffixHash: true
