resources:
- manager.yaml
- rh-ee-scondon-pull-secret.yaml
- rh-ee-scondon-google-api-key-secret.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: controller
  newName: example.com/khieron
  newTag: v0.0.1

generatorOptions:
  disableNameSuffixHash: true
