resources:
  - kueue-skill.yaml
configMapGenerator:
- name: kueue-idle-allocated-gpus
  files:
  - kueue-idle-allocated-gpus___SKILL.md=SKILL.md
  - kueue-idle-allocated-gpus___assets___kueue-advisory-tool-failed.json=assets/kueue-advisory-tool-failed.json
  - kueue-idle-allocated-gpus___assets___kueue-advisory-idle-gpu.json=assets/kueue-advisory-idle-gpu.json
  - kueue-idle-allocated-gpus___scripts___get-metrics-api.sh=scripts/get-metrics-api.sh
  - kueue-idle-allocated-gpus___scripts___get-dcgm-metrics.sh=scripts/get-dcgm-metrics.sh
  - kueue-idle-allocated-gpus___scripts___get-workload-by-pod.sh=scripts/get-workload-by-pod.sh
generatorOptions:
  disableNameSuffixHash: true