apiVersion: agency.khieron.io/v1alpha1
kind: Skill
metadata:
  labels:
    app.kubernetes.io/name: kueue-jobs-stuck
    app.kubernetes.io/managed-by: kustomize
  name: kueue-jobs-stuck
spec:
  skillconfigref:
    name: "khieron-kueue-jobs-stuck"
