---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - agency.khieron.io
  resources:
  - advisories
  - skills
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - agency.khieron.io
  resources:
  - advisories/finalizers
  - skills/finalizers
  verbs:
  - update
- apiGroups:
  - agency.khieron.io
  resources:
  - advisories/status
  - skills/status
  verbs:
  - get
  - patch
  - update
