---
skill:
  intervalMinute: 5
  enableAgent: true
serviceAccount:
  name: khieron-controller-manager
  namespace: khieron-system
mcpConfig:
  mcpJson: {
    "mcpServers": {
      "rhoai": {
      "type": "http",
      "url": "http://rhoai-mcp.rhoai-mcp.svc.cluster.local:8000/mcp",
      "name": "rhoai-mcp",
      }
    }
  }